sp:
  sample_gender/xy: 
    fn: "*_xy.tsv"
    shared : false
  sample_gender/hetx: 
    fn: "*_hetx.tsv"
    shared : false
  sample_gender/sry: 
    fn: "*_sry.tsv"
    shared : false

  coverage/summary:
    fn: "*.mosdepth.summary.txt"
    shared: false
  coverage/global_dist:
    fn: "*.mosdepth.global.dist.txt"
    shared: false
  coverage/region_dist:
    fn: "*.mosdepth.region.dist.txt"
    shared: false
  coverage/runinfo:
    fn: "*_runinfo.txt"
    shared: false

report_comment: "Panel 20X coverage has to be >=90%"

custom_plot_config:
  general_stats_table:
    defaultsort:
      - column: 20_x_pc
        direction: asc

extra_fn_clean_trim:
  - "_per_exon"

mosdepth_config:
  general_stats_coverage: [1, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
  general_stats_coverage_hidden: [1, 5, 10, 30, 40, 50, 60, 70, 80, 90, 100]

table_cond_formatting_rules:
  coverage-1_x_pc:
    pass:
      - gt: 90
      - eq: 90
    fail:
      - lt: 90
  coverage-5_x_pc:
    pass:
      - gt: 90
      - eq: 90
    fail:
      - lt: 90
  coverage-10_x_pc:
    pass:
      - gt: 90
      - eq: 90
    fail:
      - lt: 90
  coverage-20_x_pc:
    pass:
      - gt: 90
      - eq: 90
    fail:
      - lt: 90
  coverage-30_x_pc:
    pass:
      - gt: 90
      - eq: 90
    fail:
      - lt: 90
  coverage-40_x_pc:
    pass:
      - gt: 90
      - eq: 90
    fail:
      - lt: 90
  coverage-50_x_pc:
    pass:
      - gt: 90
      - eq: 90
    fail:
      - lt: 90
  coverage-60_x_pc:
    pass:
      - gt: 90
      - eq: 90
    fail:
      - lt: 90
  coverage-70_x_pc:
    pass:
      - gt: 90
      - eq: 90
    fail:
      - lt: 90
  coverage-80_x_pc:
    pass:
      - gt: 90
      - eq: 90
    fail:
      - lt: 90
  coverage-90_x_pc:
    pass:
      - gt: 90
      - eq: 90
    fail:
      - lt: 90
  coverage-100_x_pc:
    pass:
      - gt: 90
      - eq: 90
    fail:
      - lt: 90

table_cond_formatting_colours:
  - pass: "#5cb85c"
  - fail: "#d9534f"